# -*- coding: UTF-8 -*-

# Transaction types
TRANSACTION_TYPE_STOCK = 0
TRANSACTION_TYPE_BOND = 1
TRANSACTION_TYPE_CASH = 2

TRANSACTION_TYPES = [
    (TRANSACTION_TYPE_STOCK, "STOCK"),
    (TRANSACTION_TYPE_BOND, "BOND"),
    (TRANSACTION_TYPE_CASH, "CASH"),
]

# Transaction operations
TRANSACTION_OPERATION_SELL = 0
TRANSACTION_OPERATION_BUY = 1

# Transaction currencies
TRANSACTION_CURRENCY_USD = 0
TRANSACTION_CURRENCY_EUR = 1

TRANSACTION_CURRENCIES = [
    (TRANSACTION_CURRENCY_USD, "USD"),
    (TRANSACTION_CURRENCY_EUR, "EUR"),
]

# Transaction cost types
TRANSACTION_COST_FIXED = 0
TRANSACTION_COST_VARIABLE = 1

TRANSACTION_COST_TYPES = [
    (TRANSACTION_COST_FIXED, "FIXED"),
    (TRANSACTION_COST_VARIABLE, "VARIABLE"),
]

# Short position allowance (boolean)
SHORT_SELL = False

